dvb-usb-objs += dvb-usb-firmware.o dvb-usb-init.o dvb-usb-urb.o dvb-usb-i2c.o
dvb-usb-objs += dvb-usb-dvb.o dvb-usb-remote.o usb-urb.o
obj-y += dvb-usb.o

dvb-usb-tbs5520se-objs = tbs5520se.o
obj-y += dvb-usb-tbs5520se.o